create table if not exists report_archive (
    id bigint generated by default as identity primary key,
    report_type varchar(40) not null,
    report_format varchar(8) not null,
    fiscal_year_id bigint not null,
    accounting_period_id bigint,
    start_date date not null,
    end_date date not null,
    file_name varchar(255) not null,
    storage_path varchar(500) not null,
    checksum_sha256 varchar(64) not null,
    parameters clob,
    created_at timestamp not null default current_timestamp,
    constraint fk_report_archive_fiscal_year
        foreign key (fiscal_year_id) references fiscal_year(id) on delete restrict,
    constraint fk_report_archive_accounting_period
        foreign key (accounting_period_id) references accounting_period(id) on delete restrict,
    constraint ck_report_archive_type check (
        report_type in (
            'VOUCHER_LIST',
            'GENERAL_LEDGER',
            'TRIAL_BALANCE',
            'INCOME_STATEMENT',
            'BALANCE_SHEET',
            'TRANSACTION_REPORT',
            'VAT_REPORT'
        )
    ),
    constraint ck_report_archive_format check (report_format in ('PDF', 'CSV')),
    constraint uq_report_archive_storage_path unique (storage_path)
);
