create table if not exists import_job (
    id bigint generated by default as identity primary key,
    file_name varchar(255) not null,
    checksum_sha256 varchar(64) not null,
    fiscal_year_id bigint,
    status varchar(20) not null,
    summary varchar(1000),
    error_log clob,
    started_at timestamp not null default current_timestamp,
    completed_at timestamp,
    constraint fk_import_job_fiscal_year
        foreign key (fiscal_year_id) references fiscal_year(id) on delete set null,
    constraint ck_import_job_status
        check (status in ('STARTED', 'SUCCESS', 'FAILED', 'DUPLICATE'))
);
