create table if not exists closing_entry (
    id bigint generated by default as identity primary key,
    fiscal_year_id bigint not null,
    next_fiscal_year_id bigint,
    voucher_id bigint,
    entry_type varchar(32) not null,
    account_number varchar(10) not null,
    counter_account_number varchar(10),
    amount decimal(18, 2) not null,
    created_at timestamp not null,
    constraint fk_closing_entry_fiscal_year
        foreign key (fiscal_year_id) references fiscal_year(id) on delete cascade,
    constraint fk_closing_entry_next_fiscal_year
        foreign key (next_fiscal_year_id) references fiscal_year(id) on delete restrict,
    constraint fk_closing_entry_voucher
        foreign key (voucher_id) references voucher(id) on delete restrict,
    constraint fk_closing_entry_account
        foreign key (account_number) references account(account_number),
    constraint fk_closing_entry_counter_account
        foreign key (counter_account_number) references account(account_number),
    constraint ck_closing_entry_type
        check (entry_type in ('RESULT_CLOSING', 'OPENING_BALANCE'))
);
