create table if not exists company (
    id bigint generated by default as identity primary key,
    company_name varchar(200) not null,
    organization_number varchar(64) not null,
    default_currency varchar(3) not null,
    locale_tag varchar(32) not null,
    vat_periodicity varchar(20) not null default 'MONTHLY',
    active boolean not null default true,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uq_company_organization_number unique (organization_number),
    constraint ck_company_vat_periodicity check (vat_periodicity in ('MONTHLY', 'ANNUAL'))
);

insert into company (
    id,
    company_name,
    organization_number,
    default_currency,
    locale_tag,
    vat_periodicity,
    active,
    created_at,
    updated_at
)
select
    1,
    cs.company_name,
    cs.organization_number,
    cs.default_currency,
    cs.locale_tag,
    coalesce(cs.vat_periodicity, 'MONTHLY'),
    true,
    cs.created_at,
    cs.updated_at
from company_settings cs
where cs.id = 1
  and not exists (
      select 1
        from company c
       where c.id = 1
  );

insert into company (
    id,
    company_name,
    organization_number,
    default_currency,
    locale_tag,
    vat_periodicity,
    active,
    created_at,
    updated_at
)
select
    1,
    'Default company',
    '000000-0000',
    'SEK',
    'sv-SE',
    'MONTHLY',
    true,
    current_timestamp,
    current_timestamp
where not exists (
    select 1
      from company c
     where c.id = 1
);

alter table company
    alter column id restart with 2;

alter table fiscal_year
    add column if not exists company_id bigint default 1;

update fiscal_year
   set company_id = 1
 where company_id is null;

alter table fiscal_year
    add constraint fk_fiscal_year_company
        foreign key (company_id) references company(id) on delete restrict;

alter table account
    add column if not exists company_id bigint default 1;

update account
   set company_id = 1
 where company_id is null;

alter table account
    add constraint fk_account_company_foundation
        foreign key (company_id) references company(id) on delete restrict;

alter table opening_balance
    add column if not exists company_id bigint default 1;

update opening_balance ob
   set company_id = (
       select fy.company_id
         from fiscal_year fy
        where fy.id = ob.fiscal_year_id
   )
 where company_id is null;

alter table opening_balance
    add constraint fk_opening_balance_company
        foreign key (company_id) references company(id) on delete restrict;

alter table voucher
    add column if not exists company_id bigint default 1;

update voucher v
   set company_id = (
       select fy.company_id
         from fiscal_year fy
        where fy.id = v.fiscal_year_id
   )
 where company_id is null;

alter table voucher
    add constraint fk_voucher_company
        foreign key (company_id) references company(id) on delete restrict;

alter table voucher_line
    add column if not exists company_id bigint default 1;

update voucher_line vl
   set company_id = (
       select v.company_id
         from voucher v
        where v.id = vl.voucher_id
   )
 where company_id is null;

alter table voucher_line
    add constraint fk_voucher_line_company
        foreign key (company_id) references company(id) on delete restrict;

alter table attachment
    add column if not exists company_id bigint default 1;

update attachment a
   set company_id = (
       select v.company_id
         from voucher v
        where v.id = a.voucher_id
   )
 where company_id is null;

alter table attachment
    add constraint fk_attachment_company
        foreign key (company_id) references company(id) on delete restrict;

alter table audit_log
    add column if not exists company_id bigint default 1;

update audit_log al
   set company_id = coalesce(
       (
           select v.company_id
             from voucher v
            where v.id = al.voucher_id
       ),
       (
           select fy.company_id
             from fiscal_year fy
            where fy.id = al.fiscal_year_id
       ),
       (
           select a.company_id
             from attachment a
            where a.id = al.attachment_id
       ),
       1
   )
 where company_id is null;

alter table audit_log
    add constraint fk_audit_log_company
        foreign key (company_id) references company(id) on delete restrict;

alter table vat_period
    add column if not exists company_id bigint default 1;

update vat_period vp
   set company_id = (
       select fy.company_id
         from fiscal_year fy
        where fy.id = vp.fiscal_year_id
   )
 where company_id is null;

alter table vat_period
    add constraint fk_vat_period_company
        foreign key (company_id) references company(id) on delete restrict;

alter table report_archive
    add column if not exists company_id bigint default 1;

update report_archive ra
   set company_id = (
       select fy.company_id
         from fiscal_year fy
        where fy.id = ra.fiscal_year_id
   )
 where company_id is null;

alter table report_archive
    add constraint fk_report_archive_company
        foreign key (company_id) references company(id) on delete restrict;

alter table import_job
    add column if not exists company_id bigint default 1;

update import_job ij
   set company_id = coalesce(
       (
           select fy.company_id
             from fiscal_year fy
            where fy.id = ij.fiscal_year_id
       ),
       1
   )
 where company_id is null;

alter table import_job
    add constraint fk_import_job_company
        foreign key (company_id) references company(id) on delete restrict;

alter table closing_entry
    add column if not exists company_id bigint default 1;

update closing_entry ce
   set company_id = (
       select fy.company_id
         from fiscal_year fy
        where fy.id = ce.fiscal_year_id
   )
 where company_id is null;

alter table closing_entry
    add constraint fk_closing_entry_company
        foreign key (company_id) references company(id) on delete restrict;
