create table account_v15_new (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    account_number varchar(10) not null,
    account_name varchar(255) not null,
    account_class varchar(32),
    normal_balance_side varchar(16),
    vat_code varchar(32),
    active boolean not null default true,
    manual_review_required boolean not null default false,
    classification_note varchar(255),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uq_account_company_number_v15 unique (company_id, account_number),
    constraint fk_account_company_v15
        foreign key (company_id) references company(id) on delete restrict
);

insert into account_v15_new (
    company_id,
    account_number,
    account_name,
    account_class,
    normal_balance_side,
    vat_code,
    active,
    manual_review_required,
    classification_note,
    created_at,
    updated_at
)
select company_id,
       account_number,
       account_name,
       account_class,
       normal_balance_side,
       vat_code,
       active,
       manual_review_required,
       classification_note,
       created_at,
       updated_at
  from account;

-- opening_balance: switch from account_number to account_id
alter table opening_balance
    add column account_id bigint;

update opening_balance ob
   set account_id = (
       select a.id
         from account_v15_new a
        where a.company_id = ob.company_id
          and a.account_number = ob.account_number
   )
 where account_id is null;

alter table opening_balance
    alter column account_id set not null;

alter table opening_balance
    drop constraint fk_opening_balance_account;

alter table opening_balance
    drop constraint pk_opening_balance;

alter table opening_balance
    drop column account_number;

alter table opening_balance
    add constraint pk_opening_balance primary key (fiscal_year_id, account_id);

-- voucher_line: add account_id, keep account_number/account_name as snapshot
alter table voucher_line
    add column account_id bigint;

alter table voucher_line
    add column account_name varchar(255);

update voucher_line vl
   set account_id = (
       select a.id
         from account_v15_new a
        where a.company_id = vl.company_id
          and a.account_number = vl.account_number
   ),
       account_name = (
           select a.account_name
             from account_v15_new a
            where a.company_id = vl.company_id
              and a.account_number = vl.account_number
       )
 where account_id is null;

alter table voucher_line
    alter column account_id set not null;

alter table voucher_line
    drop constraint fk_voucher_line_account;

-- closing_entry: replace account_number/counter_account_number with account_id/counter_account_id
alter table closing_entry
    add column account_id bigint;

alter table closing_entry
    add column counter_account_id bigint;

update closing_entry ce
   set account_id = (
       select a.id
         from account_v15_new a
        where a.company_id = ce.company_id
          and a.account_number = ce.account_number
   ),
       counter_account_id = (
           select a.id
             from account_v15_new a
            where a.company_id = ce.company_id
              and a.account_number = ce.counter_account_number
       )
 where account_id is null;

alter table closing_entry
    alter column account_id set not null;

alter table closing_entry
    drop constraint fk_closing_entry_account;

alter table closing_entry
    drop constraint fk_closing_entry_counter_account;

alter table closing_entry
    drop column account_number;

alter table closing_entry
    drop column counter_account_number;

drop table account;

alter table account_v15_new
    rename to account;

alter table opening_balance
    add constraint fk_opening_balance_account
        foreign key (account_id) references account(id) on delete restrict;

alter table voucher_line
    add constraint fk_voucher_line_account
        foreign key (account_id) references account(id) on delete restrict;

alter table closing_entry
    add constraint fk_closing_entry_account
        foreign key (account_id) references account(id) on delete restrict;

alter table closing_entry
    add constraint fk_closing_entry_counter_account
        foreign key (counter_account_id) references account(id) on delete restrict;

alter table account
    rename constraint uq_account_company_number_v15 to uq_account_company_number;

alter table account
    drop constraint fk_account_company_v15;

alter table account
    add constraint fk_account_company
        foreign key (company_id) references company(id) on delete restrict;
