create table accounting_instruction (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    trigger_text varchar(300) not null,
    description varchar(500),
    debit_account_number varchar(20) not null,
    credit_account_number varchar(20) not null,
    series_code varchar(20) not null default 'A',
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_accounting_instruction_company
        foreign key (company_id) references company(id) on delete cascade,
    constraint uq_accounting_instruction_trigger unique (company_id, trigger_text)
);

create index ix_accounting_instruction_company on accounting_instruction(company_id);
