create table if not exists voucher_series (
    id bigint generated by default as identity primary key,
    fiscal_year_id bigint not null,
    series_code varchar(8) not null,
    series_name varchar(120) not null,
    next_running_number integer not null default 1,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_voucher_series_fiscal_year
        foreign key (fiscal_year_id) references fiscal_year(id) on delete cascade,
    constraint uq_voucher_series_code unique (fiscal_year_id, series_code),
    constraint ck_voucher_series_next_number check (next_running_number > 0)
);

create table if not exists voucher_chain_head (
    id integer primary key,
    last_content_hash varchar(64),
    updated_at timestamp not null,
    constraint ck_voucher_chain_head_singleton check (id = 1)
);

merge into voucher_chain_head (id, last_content_hash, updated_at)
key (id)
values (1, null, current_timestamp);

create table if not exists voucher (
    id bigint generated by default as identity primary key,
    fiscal_year_id bigint not null,
    voucher_series_id bigint not null,
    running_number integer,
    voucher_number varchar(40),
    accounting_date date not null,
    description varchar(500) not null,
    status varchar(20) not null,
    original_voucher_id bigint,
    previous_hash varchar(64),
    content_hash varchar(64),
    booked_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_voucher_fiscal_year
        foreign key (fiscal_year_id) references fiscal_year(id),
    constraint fk_voucher_series
        foreign key (voucher_series_id) references voucher_series(id),
    constraint fk_voucher_original
        foreign key (original_voucher_id) references voucher(id),
    constraint uq_voucher_running_number unique (fiscal_year_id, voucher_series_id, running_number),
    constraint uq_voucher_number unique (fiscal_year_id, voucher_number),
    constraint ck_voucher_status check (status in ('DRAFT', 'BOOKED', 'CANCELLED', 'CORRECTION')),
    constraint ck_voucher_running_number check (running_number is null or running_number > 0)
);

create table if not exists voucher_line (
    id bigint generated by default as identity primary key,
    voucher_id bigint not null,
    line_index integer not null,
    account_number varchar(10) not null,
    line_description varchar(500),
    debit_amount decimal(18, 2) not null default 0,
    credit_amount decimal(18, 2) not null default 0,
    created_at timestamp not null,
    constraint fk_voucher_line_voucher
        foreign key (voucher_id) references voucher(id) on delete cascade,
    constraint fk_voucher_line_account
        foreign key (account_number) references account(account_number),
    constraint uq_voucher_line_index unique (voucher_id, line_index),
    constraint ck_voucher_line_amounts
        check (debit_amount >= 0 and credit_amount >= 0 and not (debit_amount > 0 and credit_amount > 0))
);
