alter table voucher_chain_head
    alter column updated_at set default current_timestamp;

create table if not exists attachment (
    id bigint generated by default as identity primary key,
    voucher_id bigint not null,
    original_file_name varchar(255) not null,
    content_type varchar(200),
    storage_path varchar(500) not null,
    checksum_sha256 varchar(64) not null,
    file_size bigint not null,
    created_at timestamp not null,
    constraint fk_attachment_voucher
        foreign key (voucher_id) references voucher(id) on delete restrict,
    constraint uq_attachment_storage_path unique (storage_path),
    constraint ck_attachment_file_size check (file_size >= 0)
);

create table if not exists audit_log (
    id bigint generated by default as identity primary key,
    event_type varchar(50) not null,
    voucher_id bigint,
    attachment_id bigint,
    fiscal_year_id bigint,
    accounting_period_id bigint,
    actor varchar(120) not null,
    summary varchar(500) not null,
    details clob,
    previous_hash varchar(64),
    entry_hash varchar(64) not null,
    created_at timestamp not null,
    constraint fk_audit_log_voucher
        foreign key (voucher_id) references voucher(id) on delete restrict,
    constraint fk_audit_log_attachment
        foreign key (attachment_id) references attachment(id) on delete restrict,
    constraint fk_audit_log_fiscal_year
        foreign key (fiscal_year_id) references fiscal_year(id) on delete restrict,
    constraint fk_audit_log_period
        foreign key (accounting_period_id) references accounting_period(id) on delete restrict
);
