create table if not exists vat_period (
    id bigint generated by default as identity primary key,
    fiscal_year_id bigint not null,
    period_index integer not null,
    period_name varchar(40) not null,
    start_date date not null,
    end_date date not null,
    status varchar(20) not null default 'OPEN',
    report_hash varchar(64),
    reported_at timestamp,
    locked_at timestamp,
    transfer_voucher_id bigint,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_vat_period_fiscal_year
        foreign key (fiscal_year_id) references fiscal_year(id) on delete cascade,
    constraint fk_vat_period_transfer_voucher
        foreign key (transfer_voucher_id) references voucher(id) on delete restrict,
    constraint uq_vat_period_index unique (fiscal_year_id, period_index),
    constraint ck_vat_period_status check (status in ('OPEN', 'REPORTED', 'LOCKED'))
);
