package se.alipsa.accounting.service

import groovy.transform.PackageScope

import se.alipsa.accounting.domain.Company
import se.alipsa.accounting.domain.LegalForm
import se.alipsa.accounting.domain.SruSignCondition
import se.alipsa.accounting.domain.SruSuggestion

/**
 * Looks up suggested SRU field codes for an account, from the CSV tables generated by
 * BasSruTableConverter (see docs/SRU/SOURCES.md). Advisory only - never auto-applied.
 */
final class SruSuggestionService {

  private final Map<String, Map<String, List<SruSuggestion>>> tablesByResource = [:]

  List<SruSuggestion> suggest(Company company, String accountNumber) {
    if (company == null || company.legalForm == null) {
      return []
    }
    Map<String, List<SruSuggestion>> table = loadTable(resourceNameFor(company.legalForm, company.simplifiedAnnualReport))
    table.getOrDefault(accountNumber, [])
  }

  @PackageScope
  int tableSizeForTesting(LegalForm legalForm, boolean simplifiedAnnualReport) {
    loadTable(resourceNameFor(legalForm, simplifiedAnnualReport)).values()*.size().sum() as int
  }

  private static String resourceNameFor(LegalForm legalForm, boolean simplifiedAnnualReport) {
    switch (legalForm) {
      case LegalForm.AKTIEBOLAG: return 'ink2.csv'
      case LegalForm.HANDELSBOLAG_KB: return 'ink4.csv'
      case LegalForm.ENSKILD_FIRMA: return simplifiedAnnualReport ? 'ne_k1.csv' : 'ne_ej_k1.csv'
      default: throw new IllegalStateException("Unhandled legal form: ${legalForm}")
    }
  }

  private synchronized Map<String, List<SruSuggestion>> loadTable(String resourceName) {
    tablesByResource.computeIfAbsent(resourceName) { String name -> readCsv(name) }
  }

  private static Map<String, List<SruSuggestion>> readCsv(String resourceName) {
    Map<String, List<SruSuggestion>> table = [:]
    SruSuggestionService.getResourceAsStream("/sru/${resourceName}").withReader('UTF-8') { reader ->
      reader.readLine() // header
      String line
      while ((line = reader.readLine()) != null) {
        if (!line.trim()) {
          continue
        }
        String[] parts = line.split(',', 4)
        String fieldCode = parts[0]
        String accountNumber = parts[1]
        SruSignCondition sign = parts[2] as SruSignCondition
        String description = parts.length > 3 ? parts[3] : ''
        table.computeIfAbsent(accountNumber) { [] } << new SruSuggestion(fieldCode, description, sign)
      }
    }
    table
  }
}
